### ISSUE TITLE
Table "USER" not found; SQL statement:

### ISSUE THREAD

**Issue by dereklin** [mrin9/Angular2_SpringBoot#12]
I am on window 10.

I am getting this error when starting the app:

```
Caused by: org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
```
```
        ... 59 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
insert into user (user_id, password, first_name, last_name, email, company, phone, address1, address2, country, postal, role, is_active, is_blocked, security_provider_id, default_customer_id, secret_question, secret_answer, enable_beta_testing, enable_renewal) values ('demo' , 'demo' , 'Mrinmoy' , 'Majumdar', 'arivera2@joomla.org' , 'Abshire Inc', '7-(740)701-4547', '80429 Garrison Crossing', '4967' , 'USA' , '64890', 'USER' , 1, 0, 10001, 20000, 'Diverse' , 'Yellow' , 0, 0), ('admin' , 'admin' , 'Theresa' , 'Russell' , 'trussell1@about.me' , 'Glover, Adams and Bins', '383-(779)851-3208', '30874 Graceland Terrace', '99152' , 'USA' , '51065', 'ADMIN', 1, 0, 10001, 20000, 'knowledge base', 'Mauv' , 1, 0), ('user' , 'user' , 'Virginia' , 'Reynolds', 'vreynolds0@slashdot.org', 'Rippin, Osinski and Beatty', '84-(228)809-9998', '0118 Burrows Plaza', '496' , 'USA' , '94086', 'USER' , 1, 0, 10001, 20000, 'Innovative' , 'Turquoise', 1, 1), ('jowens3' , 'jowens3' , 'Judy' , 'Owens' , 'jowens3@hp.com' , 'Altenwerth, Fisher and Heidenreich', '30-(772)268-8227', '98 Loeprich Way', '447', 'Greece' , null , 'USER' , 0, 0, 10001, 20001, 'capacity' , 'Fuscia' , 1, 1), ('kburns4' , 'kburns4' , 'Kelly' , 'Burns' , 'kburns4@icio.us' , 'McCullough-Morar', '86-(857)185-5740', '1638 Basil Alley', '56297' , 'China' , null , 'ADMIN', 1, 0, 10000, 20002, 'user-facing' , 'Crimson', 1, 1), ('jshaw5' , 'jshaw5' , 'Julie' , 'Shaw' , 'jshaw5@opera.com' , 'Steuber-Okuneva', '1-(871)375-6188', '389 Myrtle Pass', '41444' , 'Canada' , null , 'ADMIN', 1, 1, 10000, 20000, 'software' , 'Green' , 0, 1), ('pgilbert6' , 'pgilbert6', 'Peter' , 'Gilbert' , 'pgilbert6@eepurl.com' , 'Robel Inc', '52-(372)555-4687', '11522 Fuller Avenue', '5' , 'Mexico' , '39230', 'ADMIN', 1, 1, 10000, 20000, 'multi-state' , 'Puce' , 1, 1), ('jjacobs7' , 'jjacobs7' , 'Justin' , 'Jacobs' , 'jjacobs7@google.co.uk' , 'Harris-Bashirian', '963-(199)359-2552', '95012 Hanover Street', '2377' , 'India' , null , 'USER' , 1, 0, 10000, 20002, 'motivating' , 'Crimson', 1, 0), ('kbennett8' , 'kbennett8', 'Kevin' , 'Bennett' , 'kbennett8@hostgator.com', 'Leannon Inc', '62-(892)710-5713', '459 Coleman Drive', '397' , 'Indonesia' , null , 'ADMIN', 0, 0, 10001, 20000, 'Exclusive' , 'Purple' , 1, 1), ('cmurphy9' , 'cmurphy9' , 'Chris' , 'Murphy' , 'cmurphy9@over-blog.com' , 'Mosciski LLC', '64-(272)961-0086', '2 Ludington Point', '7' , 'New Zealand', null , 'ADMIN', 0, 1, 10000, 20000, 'empowering' , 'Maroon' , 0, 1) [42102-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.readTableOrView(Parser.java:5552) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.readTableOrView(Parser.java:5529) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.parseInsert(Parser.java:1062) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.parsePrepared(Parser.java:417) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.parse(Parser.java:321) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.parse(Parser.java:293) ~[h2-1.4.196.jar!/:na]
        at org.h2.command.Parser.prepareCommand(Parser.java:258) ~[h2-1.4.196.jar!/:na]
        at org.h2.engine.Session.prepareLocal(Session.java:578) ~[h2-1.4.196.jar!/:na]
        at org.h2.engine.Session.prepareCommand(Session.java:519) ~[h2-1.4.196.jar!/:na]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204) ~[h2-1.4.196.jar!/:na]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176) ~[h2-1.4.196.jar!/:na]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164) ~[h2-1.4.196.jar!/:na]
        at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:470) ~[spring-jdbc-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        ... 79 common frames omitted


```

**Comment by mrin9** [comment]
I am sorry i am unable to reproduce your issue on my end. may be a system or environment issue

Try to change the case of table names to upper case in 
[schema.sql](https://github.com/mrin9/Angular-SpringBoot-REST-JWT/blob/master/src/main/resources/schema.sql)
[data.sql](https://github.com/mrin9/Angular-SpringBoot-REST-JWT/blob/master/src/main/resources/data.sql)

**Comment by narendraamilineni** [comment]
I too faced same problem. And i found some solution for mine. Please see if it useful.

Try to maintain SpringStartApplication in first package in below way to resolve your problem and it has to be the first class. I feel SpringBoot using some ordering

org.naren.spring.ms.app
        SpringStartApplication.java
org.naren.spring.ms.data.model
        Program1.java

**Comment by tokiodeo** [comment]
@Table(name="[user]")   in Model Entity
