### ISSUE TITLE
 Metadata version mismatch for module @swimlane (found version 4, expected 3)

### ISSUE THREAD

**Issue by tschmidt01** [mrin9/Angular2_SpringBoot#13]
```
npm install
ng build -prod --aot=false
```
leads to the following error:
```
ERROR in Error: Metadata version mismatch for module /Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@swimlane/ngx-datatable/release/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/src/app/app.module.ts, resolving symbol AppModule in /Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/src/app/app.module.ts
    at syntaxError (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/Thomas/Desktop/Angular-SpringBoot-REST-JWT-master/webui/node_modules/@ngtools/webpack/src/plugin.js:495:24)
```

**Comment by mrin9** [comment]
upgraded to Angular 5.1.0-beta.0 and Angular CLI 1.6.0-beta.0
having those installed properly
try using ```ng build  --aot=false```
Do not use ```--prod``` or ``` --aot=true``` as the current version of ngx-datatable have some issues with it
